# Generated by Django 4.0.6 on 2022-07-15 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fist_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('Address', models.TextField(max_length=13)),
                ('email', models.EmailField(max_length=15)),
                ('phone_number', models.CharField(max_length=13)),
                ('gender', models.CharField(max_length=8)),
            ],
        ),
    ]
