# Generated by Django 4.0.6 on 2022-07-30 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_customer_wallet_delete_customers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wallet',
        ),
    ]
