# Generated by Django 4.0.6 on 2022-07-30 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_delete_wallet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=30)),
                ('amount', models.IntegerField()),
                ('balance', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('status', models.CharField(max_length=200)),
                ('pin', models.TextField(default='', max_length=12)),
                ('history', models.DateTimeField()),
                ('Customers_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallet.customer')),
            ],
        ),
    ]
