# Generated by Django 4.0.6 on 2022-08-02 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0009_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_description',
            field=models.CharField(max_length=270),
        ),
    ]
