# Generated by Django 4.0.6 on 2022-08-19 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0016_reward'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='transaction_charge',
        ),
    ]
